import Navbar from '@/components/layouts/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Work_Sans } from 'next/font/google'
import Footer from '@/components/layouts/Footer'
import Script from 'next/script'

const work_wans = Work_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Vimoni',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={work_wans.className}>
        <Navbar />
        {children}
        <Footer />
        <Script id="btn-script">
          {`
            const btnShadow = document.querySelectorAll('.btn-shadow');
            btnShadow.forEach((btn) => {
              btn.addEventListener(('click'), (e) => {
                btn.classList.add('active');
              })
            });

            const pluginShadowBtn = document.querySelectorAll('.plugin-shadow');
            pluginShadowBtn.forEach((btn) => {
              btn.addEventListener(('click'), (e) => {
                btn.classList.add('active');
              })
            });
          `}
        </Script>
      </body>
    </html>
  )
}
