import Image from "next/image";
import { BsServer } from "react-icons/bs";

const ApiPage = () => {
  return (
    <div className="relative flex justify-between container w-full  px-[200px] pt-28 pb-56">
      <div className="inset-0 absolute h-full w-[256px] bg-[#e8e9ed] py-20 px-12 flex flex-col justify-start gap-8">
          <h3 className="text-xl text-theme-primary font-semibold">
            AUTORYZACJA
          </h3>
        <div className="flex flex-col border-t-2 border-[#d8d8dc] text-theme-text w-[68px] pt-8 gap-6">
          <a>Terminale</a>
          <a>Transakcje</a>
        </div>
      </div>
      <div className="flex flex-col gap-8">
        <div className="flex flex-row gap-10">
          <div className="text-[#d4d5d9]">
            <BsServer size={"64"} />
          </div>
          <div className="flex flex-col gap-2">
            <h1 className="text-theme-primary underline underline-offset-4 font-bold text-3xl">
              Utwórz transakcję
            </h1>
            <p className="text-theme-text w-[640px]">
              Pozwala na utworzenie transakcji (przesyłając parametry transakcji
              do ZEN). Ważne! Dla niektórych metod płatności zostanie zwrócony
              returnUrl. Aby kontynuować transakcję, klient musi zostać
              przekierowany pod ten adres URL.
            </p>
          </div>
        </div>
        <div className="text-2xl flex flex-row gap-4">
          <h2 className="text-theme-primary font-semibold text-xl">
            AUTHORIZATIONS
          </h2>
          <h3 className="text-base text-[#0000ff] place-self-center">
            ApiKey
          </h3>
        </div>
        <div className="flex flex-col gap-6">
          <div className="border-b-2 border-[#d8d8dc]">
            <h2 className="text-theme-primary font-semibold text-xl">
              HEADER PARAMETERS
            </h2>
          </div>
          <div className="flex flex-row gap-10">
              <p className="text-theme-text w-[100px]">
                request-id
              </p>
              <div className="flex flex-col gap-4 w-full border-b-2 border-[#d8d8dc] pb-4">
                <div className="flex flex-row gap-4">
                  <p className="text-theme-text">string</p>
                  <p className="text-[#0000ff] bg-[#d4d5d9] px-2 mr-2">[ 38 . . 1024 . ] characters</p>
                  <p className="text-[#008000]">^[a-zA-Z0-978_|\</p>
                </div>
                <div className="flex flex-col">
                  <p className="text-theme-text">Example: <a className="bg-[#d4d5d9]">un04oqdn=FQVr0r109/e90VDRE2BXVEWOLV</a></p>
                  <p className="text-theme-text">A unique identifier generated by requesting client</p>
                </div>
              </div>
          </div>
        </div>
        <div className="text-2xl flex flex-row gap-4 border-b-2 border-[#d8d8dc]">
          <h2 className="text-theme-primary font-semibold text-xl">
            REQUEST BODY SCHEMA
          </h2>
          <h3 className="text-base text-theme-text place-self-center">
            application/json
          </h3>
        </div>
      </div>
      <div className="absolute -right-[190px] top-28 flex w-[376px] h-[638px]">
        <Image src="/images/RightPane.png" alt="Placeholder" fill={true} />
      </div>
    </div>
  );
};

export default ApiPage;
